# Generated by Django 5.2.15 on 2026-06-06 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('vendor_created', 'Vendor Created'), ('vendor_updated', 'Vendor Updated'), ('vendor_deleted', 'Vendor Deleted'), ('rfq_created', 'RFQ Created'), ('rfq_published', 'RFQ Published'), ('rfq_cancelled', 'RFQ Cancelled'), ('quotation_submitted', 'Quotation Submitted'), ('quotation_updated', 'Quotation Updated'), ('vendor_selected', 'Vendor Selected'), ('approval_submitted', 'Submitted for Approval'), ('approval_approved', 'Approval Approved'), ('approval_rejected', 'Approval Rejected'), ('po_generated', 'PO Generated'), ('po_issued', 'PO Issued'), ('po_completed', 'PO Completed'), ('invoice_generated', 'Invoice Generated'), ('invoice_paid', 'Invoice Marked Paid'), ('report_exported', 'Report Exported'), ('comparison_viewed', 'Quotation Comparison Viewed')], max_length=30)),
                ('description', models.TextField()),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_name', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
