# Generated by Django 5.2.15 on 2026-06-06 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery_days', models.IntegerField(default=7)),
                ('payment_terms', models.CharField(choices=[('advance', '100% Advance'), ('net15', 'Net 15 Days'), ('net30', 'Net 30 Days'), ('net45', 'Net 45 Days'), ('net60', 'Net 60 Days'), ('50_50', '50% Advance, 50% on Delivery'), ('on_delivery', '100% on Delivery')], default='net30', max_length=20)),
                ('warranty_period', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_selected', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['grand_total'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('submitted', 'Submitted'), ('l1_review', 'L1 Manager Review'), ('l2_approval', 'L2 Finance Approval'), ('procurement_head', 'Procurement Head'), ('generate_po', 'Generate PO'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='approvals.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('submitted', 'Submitted'), ('l1_review', 'L1 Manager Review'), ('l2_approval', 'L2 Finance Approval'), ('procurement_head', 'Procurement Head'), ('generate_po', 'Generate PO'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('action', models.CharField(choices=[('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded'), ('returned', 'Returned for Revision'), ('escalated', 'Escalated')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalworkflow')),
            ],
            options={
                'ordering': ['acted_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('IT', 'IT & Technology'), ('OFFICE', 'Office Supplies'), ('MANUFACTURING', 'Manufacturing'), ('SERVICES', 'Professional Services'), ('LOGISTICS', 'Logistics & Transport'), ('CONSTRUCTION', 'Construction & Infra'), ('OTHER', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('evaluation', 'Under Evaluation'), ('awarded', 'Awarded'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='approvals.rfq'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='approvals.rfq'),
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('ltr', 'Litres'), ('mtr', 'Metres'), ('box', 'Box'), ('set', 'Set'), ('unit', 'Unit'), ('nos', 'Numbers')], default='pcs', max_length=10)),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('specifications', models.TextField(blank=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='approvals.rfq')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='approvals.quotation')),
                ('rfq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.rfqitem')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=15)),
                ('category', models.CharField(choices=[('IT', 'IT & Technology'), ('OFFICE', 'Office Supplies'), ('MANUFACTURING', 'Manufacturing'), ('SERVICES', 'Professional Services'), ('LOGISTICS', 'Logistics & Transport'), ('CONSTRUCTION', 'Construction & Infra'), ('OTHER', 'Other')], max_length=30)),
                ('payment_terms', models.CharField(default='Net 30', max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rating', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted'), ('pending', 'Pending Approval')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.AddField(
            model_name='rfq',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='rfqs', to='approvals.vendor'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='approvals.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('rfq', 'vendor')},
        ),
    ]
